"""create products table

Revision ID: 019d1a6121dc
Revises: 20260427_0002
Create Date: 2026-04-27 09:59:14.625656
"""

from alembic import op
import sqlalchemy as sa



revision = '019d1a6121dc'
down_revision = '20260427_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
