"""fix user timestamps

Revision ID: 2c3e0b350145
Revises: 20260427_0003
Create Date: 2026-04-27 10:31:21.989978
"""

from alembic import op
import sqlalchemy as sa



revision = '2c3e0b350145'
down_revision = '20260427_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
    )
    op.add_column(
        'users',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
    )
    op.alter_column('users', 'created_at', server_default=None)
    op.alter_column('users', 'updated_at', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
