"""add order_number to orders table 

Revision ID: 50b946135e34
Revises: a834f2b943ff
Create Date: 2026-04-30 19:31:34.786814
"""

from alembic import op
import sqlalchemy as sa



revision = '50b946135e34'
down_revision = 'a834f2b943ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_column('orders', 'order_number')
    # ### end Alembic commands ###
