"""create orderDetails table 

Revision ID: a834f2b943ff
Revises: ce0afa689a92
Create Date: 2026-04-30 19:29:27.788300
"""

from alembic import op
import sqlalchemy as sa



revision = 'a834f2b943ff'
down_revision = 'ce0afa689a92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderDetails',
    sa.Column('OrderDetail_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('OrderDetail_id')
    )
    op.create_index(op.f('ix_orderDetails_OrderDetail_id'), 'orderDetails', ['OrderDetail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderDetails_OrderDetail_id'), table_name='orderDetails')
    op.drop_table('orderDetails')
    # ### end Alembic commands ###
