"""update create_at and update_at to orders table 

Revision ID: ce0afa689a92
Revises: 8df62cc15dd5
Create Date: 2026-04-30 19:17:37.084982
"""

from alembic import op
import sqlalchemy as sa



revision = 'ce0afa689a92'
down_revision = '8df62cc15dd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
